# Generated by Django 2.2.25 on 2022-01-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginAndRegistration', '0003_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='receiver_username',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender_username',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
